version: 2.1
orbs:
   node: circleci/node@5.1.1
jobs:
   test:
      docker:
         - image: 'cimg/node:18.18-browsers'
      steps:
         - checkout
         - node/install:
              node-version: '20'
         - node/install-packages
         - run:
              command: npm run test -- --ci --reporters=default --reporters=jest-junit
              environment:
                 JEST_JUNIT_OUTPUT_FILE: 'reports/junit/js-test-results.xml'
         - store_test_results:
            path: reports/junit
workflows:
   build-and-test:
      jobs:
         - test
